default_language_version:
    python: python3.10

default_stages: [commit]

repos:

    -   repo: https://github.com/commitizen-tools/commitizen
        rev: v2.23.0
        hooks:
        -   id: commitizen
            stages: [commit-msg]

    -   repo: https://github.com/pre-commit/mirrors-autopep8
        rev: v1.7.0
        hooks:
        -   id: autopep8
            files: ^src/

    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
        - id: check-ast
          description: Simply check whether files parse as valid python
        - id: check-case-conflict
          description: Check for files that would conflict in case-insensitive filesystems
        - id: check-docstring-first
          description: Checks for a common error of placing code before the docstring.
        - id: check-merge-conflict
          description: Check for files that contain merge conflict strings
        - id: check-yaml
          description: Attempts to load all yaml files to verify syntax
        - id: debug-statements
          description: Check for debugger imports and py37+ breakpoint() calls in python source
        - id: end-of-file-fixer
          description: Makes sure files end in a newline and only a newline
        - id: trailing-whitespace
          description: Trims trailing whitespace
        - id: mixed-line-ending
          description: Replaces or checks mixed line ending

    -   repo: https://github.com/asottile/add-trailing-comma
        rev: v2.2.3
        hooks:
        -   id: add-trailing-comma

    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.74.1
      hooks:
        - id: terraform_fmt
          files: ^terraform/
        - id: terraform_docs
          files: ^terraform/
        - id: terraform_checkov
          files: ^terraform/
        - id: terraform_tflint
          files: ^terraform/

    - repo: https://github.com/pycqa/pylint
      rev: v2.12.2
      hooks:
        -   id: pylint
            files: (^src/)
            args: ["--rcfile=pylint.rc", "--disable=import-error"]

    -   repo: https://github.com/pycqa/flake8
        rev: 5.0.1
        hooks:
        -   id: flake8
            additional_dependencies:
                [
                    flake8-bugbear,
                    flake8-builtins,
                    flake8-cognitive-complexity,
                    flake8-commas,
                    flake8-functions,
                    flake8-import-order,
                    flake8-polyfill,
                ]

    -   repo: https://github.com/kynan/nbstripout
        rev: 0.5.0
        hooks:
        -    id: nbstripout
             files: ".ipynb$"
